import Head from 'next/head'

import { CourseCard } from '../components/CourseCard/CourseCard.view'

export default function CoursesDemo() {
  const courses = [
    {
      courseName: 'Pronghord Club',
      location: 'Bend, OR',
      rating: 95,
      imgUrl: 'images/pronghorn.jpg',
    },
    {
      courseName: 'Bend Country Club',
      location: 'Bend, OR',
      rating: 75,
      imgUrl: 'images/bend-gcc.jpg',
    },
    {
      courseName: 'Awbrey Glen Golf Club',
      location: 'Bend, OR',
      rating: 85,
      imgUrl: 'images/awbrey_glen_golf_club-bend.jpg',
    },
    {
      courseName: 'Brasada Ranch',
      location: 'Bend, OR',
      rating: 80,
      imgUrl: 'images/brasada_ranch.jpg',
    },
    {
      courseName: 'Broken Top',
      location: 'Bend, OR',
      rating: 85,
      imgUrl: 'images/broken_top-bend.jpg',
    },
    {
      courseName: 'Crosswater',
      location: 'Sun River, OR',
      rating: 85,
      imgUrl: 'images/crosswater.jpg',
    },
    {
      courseName: 'Juniper Golf Club',
      location: 'Redmond, OR',
      rating: 85,
      imgUrl: 'images/juniper.jpg',
    },
    {
      courseName: 'Tetherow Golf Club',
      location: 'Bend, OR',
      rating: 85,
      imgUrl: 'images/tetherow-bend-or.jpg',
    },
  ]

  const coursesList = courses.map((course, ix) => (
      <div key={ix}
        style={{margin: '10px 20px'}}>
      <CourseCard
        courseName={course.courseName}
        location={course.location}
        rating={course.rating}
        imgUrl={course.imgUrl}
      />
    </div>
  ))

  return (
    <>
      <Head>
        <title>{'Provisional 🏌🏻‍♂️'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {coursesList}
    </>
  )
}
