import Head from 'next/head'
import Link from 'next/link'
import { motion } from 'framer-motion'
import { CourseCard } from '../components/CourseCard/CourseCard.view'

export default function CoursesDemo() {
  const variants = {
    hidden: { opacity: 0, x: -200, y: 0 },
    enter: { opacity: 1, x: 0, y: 0 },
    exit: { opacity: 0, x: 0, y: -100 },
  }

  const container = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: {
        staggerChildren: 0.2
      }
    }
  }
  
  const item = {
    hidden: { opacity: 0, x: -200 },
    show: { opacity: 1, x: 0 }
  }

  const courses = [
    {
      courseName: 'Pronghorn Club',
      location: 'Bend, OR',
      rating: 95,
      imgUrl: 'images/pronghorn.jpg',
    },
    {
      courseName: 'Bend Country Club',
      location: 'Bend, OR',
      rating: 75,
      imgUrl: 'images/bend-gcc.jpg',
    },
    {
      courseName: 'Awbrey Glen Golf Club',
      location: 'Bend, OR',
      rating: 85,
      imgUrl: 'images/awbrey_glen_golf_club-bend.jpg',
    },
    {
      courseName: 'Brasada Ranch',
      location: 'Bend, OR',
      rating: 80,
      imgUrl: 'images/brasada_ranch.jpg',
    },
    {
      courseName: 'Broken Top',
      location: 'Bend, OR',
      rating: 85,
      imgUrl: 'images/broken_top-bend.jpg',
    },
    {
      courseName: 'Crosswater',
      location: 'Sun River, OR',
      rating: 85,
      imgUrl: 'images/crosswater.jpg',
    },
    {
      courseName: 'Juniper Golf Club',
      location: 'Redmond, OR',
      rating: 85,
      imgUrl: 'images/juniper.jpg',
    },
    {
      courseName: 'Tetherow Golf Club',
      location: 'Bend, OR',
      rating: 85,
      imgUrl: 'images/tetherow-bend-or.jpg',
    },
  ]

  const coursesList = courses.map((course, ix) => (
    <motion.div key={ix} variants={item}>
      <CourseCard
        courseName={course.courseName}
        location={course.location}
        rating={course.rating}
        imgUrl={course.imgUrl}
      />
    </motion.div>
  ))

  return (
    <>
      <Head>
        <title>{'Provisional 🏌🏻‍♂️'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ textAlign: 'center', padding: '10px' }}>
        <motion.main
          variants={variants} // Pass the variant object into Framer Motion
          initial="hidden" // Set the initial state to variants.hidden
          animate="enter" // Animated state to variants.enter
          exit="exit" // Exit state (used later) to variants.exit
          transition={{ type: 'linear' }} // Set the transition to linear
          className=""
        >
          <Link href="/">Home</Link>
          <motion.ul variants={container} initial="hidden" animate="show" >

          {coursesList}
          </motion.ul>
        </motion.main>
      </div>
    </>
  )
}
