import Head from 'next/head'
import Image from 'next/image'
/** supabase provides user auth and database */
import { Auth, ThemeSupa } from '@supabase/auth-ui-react'
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react'

import Account from '../components/Account/Account.view'

import styles from '../styles/Home.module.css'

export default function Home() {
  const session = useSession()
  const supabase = useSupabaseClient()

  return (
    <div className={styles.container}>
      <Head>
        <title>{'Provisional 🏌🏻‍♂️'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{'Provisional 🏌🏻‍♂️'}</h1>

        <p className={styles.description}>
          {"Track courses you've played."}
          <br />
          {'Save ones you want to play.'}
          <br />
          {"Tell your friends where's good."}
        </p>
        {!session ? (
          <Auth
            supabaseClient={supabase}
            appearance={{ theme: ThemeSupa }}
            theme="dark"
          />
        ) : (
          <Account session={session} />
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
